name: CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: 📥 Install dependencies
        run: bun install

      - name: 🧪 Run tests
        run: bun run test

      - name: 🔎 Type check
        run: bun run tscheck
